### ISSUE TITLE
Resource part path not specified correctly for sub-resources

### ISSUE THREAD

**Issue by robertdfrench** [robertdfrench/psychic-disco#12]
Try creating `/blarg` and then adding a new route like `/blarg/by_blargname`

**Comment by robertdfrench** [comment]
when calling `psychic_disco deploy_new_routes <api-name>`:

```
Updating build_manager-list_builds
        Deploying Resource: /builds/by_trial
        Deploying Resource: /builds
                Deploying Method: GET
Updating build_manager-list_builds
Traceback (most recent call last):
  File "/usr/local/bin/psychic_disco", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ec2-user/Projects/psychic-disco/bin/psychic_disco", line 90, in <module>
    args.func(args)
  File "/home/ec2-user/Projects/psychic-disco/psychic_disco/cli.py", line 29, in <lambda>
    sp.set_defaults(func=lambda args: _apply_args_to_func(args, f))
  File "/home/ec2-user/Projects/psychic-disco/psychic_disco/cli.py", line 17, in _apply_args_to_func
    return func(**local_args)
  File "/home/ec2-user/Projects/psychic-disco/bin/psychic_disco", line 22, in deploy_new_routes
    api.deploy()
  File "/home/ec2-user/Projects/psychic-disco/psychic_disco/api_gateway_config.py", line 107, in deploy
    resource.deploy()
  File "/home/ec2-user/Projects/psychic-disco/psychic_disco/api_gateway_config.py", line 170, in deploy
    pathPart=self.path_part)
  File "/usr/local/lib/python2.7/site-packages/botocore-1.4.10-py2.7.egg/botocore/client.py", line 236, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore-1.4.10-py2.7.egg/botocore/client.py", line 500, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (BadRequestException) when calling the CreateResource operation: Resource's path part only allow a-zA-Z0-9._- and curly braces at the beginning and the end.
```
